name:                reversi
version:             0.1.0.0
license:             BSD3

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- containers
- optparse-applicative
- random
- stm
- vector
- vector-instances

library:
  source-dirs: src

executables:
  reversi-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -fspecialise-aggressively
    - -fexpose-all-unfoldings
    - -funfolding-use-threshold=64
    - -optc-O3
    dependencies:
    - reversi

# tests:
#   reversi-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - reversi
